### ISSUE TITLE
Objects loaded from config - But not spawned properly

### ISSUE THREAD

**Issue by ConradWeiser** [LazDisco/FLHook#4]
SpaceObjects when fed a filepath, load information from the .ini file to create a filled `SpaceObject` object.

However, the system isn't spawning the new solar in space correctly after constructing the object.

Reference line 32 of `SpaceObject.cpp` for `Spawn()` code.
I suspect data is still missing from the `Load()` code on line 172, which isn't allowing the spawn function to run completely.

**Comment by LazDisco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Objects loaded from configuration, but not spawned](https://trello.com/c/UDSV1nNi/2-objects-loaded-from-configuration-but-not-spawned)

**Comment by ConradWeiser** [comment]
Resolved in 6927598
