### ISSUE TITLE
SolarCntl refuses to unload completely

### ISSUE THREAD

**Issue by ConradWeiser** [LazDisco/FLHook#5]
After `unloadplugin SolarCntl` is run in the console, we get an "OK" message saying that everything is fine. However the .dll file cannot be replaced, or removed, suggesting that it's still in use by FLServer.

I suspect a file operation isn't being closed in either the `Save` or `Load` function for some reason.

**Comment by LazDisco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Plugin refuses to unload completely](https://trello.com/c/4cXbsrcg/1-plugin-refuses-to-unload-completely)

**Comment by ConradWeiser** [comment]
Resolved. I don't know how, but suddenly this issue went away.
