### ISSUE TITLE
Using .rehash crashes the server

### ISSUE THREAD

**Issue by LazDisco** [LazDisco/FLHook#6]
An exception is being thrown due to a 'read access violation. obj was a nullptr'.:

https://github.com/LazDisco/FLHook/blob/06453533d607f3f8de2b4ba982a9cf21b3448dea/Plugins/Public/SolarController/Main.cpp#L255

Attached image for better clarity.

![alt text](https://i.imgur.com/uytWgkg.png "Exception:")

**Comment by LazDisco** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Using .rehash crashes the server](https://trello.com/c/9ancBtet/12-using-rehash-crashes-the-server)

**Comment by ConradWeiser** [comment]
Rehash causes major problems with other plugins too. The lesson: Don't use rehash
No real need to implement support for such a thing. If anything, disable rehash support.

**Comment by LazDisco** [comment]
For what it's worth, resolved in 3b8c4b9.
